### ISSUE TITLE
Manuscript Review

### ISSUE THREAD

**Issue by amkrajewski** [mcgalcode/pylattica#14]
Here is a list of comments regarding the manuscript (living in the [paper branch](https://github.com/mcgalcode/pylattica/tree/paper)) for my review of your JOSS submission. 

- **The manuscript reads well, both in terms of contents and style. It introduces the core functionality of _pylattica_ software and explains the motivation for creating an extensible platform that can help prototype new methods and, at the same time, keep them consistent with each other to improve reusability.**

- The interaction with `pymatgen` and the degree to which it underlies the software seems a bit glossed over in the manuscript. In particular, [parts dealing with lattice](https://github.com/mcgalcode/pylattica/blob/9b6d8f43b0f269576b720826257ae2eb5652153b/src/pylattica/core/lattice.py) are largely directly copied from there, which is perfectly ok and great for extensibility, but (1) should be explicitly mentioned in publication and (2) `pymatgen`'s MIT license notice has to be attached to the codebase.

- *(L17)* - Typo? It seems it should have been "state of the neighborhood."

- *(L42-46)* - These two sentences are a bit confusing and also slightly redundant in the information they carry. A quick rewriting from scratch may help.

- *(Sec. Simulation Execution*) - A simple flowchart would be helpful in visualizing how different classes interoperate. 

- The way the neighborhood between sites is established should be discussed in more detail. The [current codebase](https://github.com/mcgalcode/pylattica/blob/9b6d8f43b0f269576b720826257ae2eb5652153b/src/pylattica/core/neighborhood_builders.py) is hard-coded to use either Motiffs or Cartesian distance sphere as the cutoff, and it may be a limiting factor in some cases. Allowing more custom Voronoi tesselation and other methods wrapped into the `pymatgen` structure analysis toolset may be more future-proof.

- *(L93)* - The "SimulationStep" is (1) not a monospace `code` block, breaking style from the rest of the manuscript, and has not been introduced earlier, nor did I see it in the code. Perhaps an error? `SimulationState` seemingly fits here.

**Comment by mcgalcode** [comment]
Hi @amkrajewski! Thanks for your review - I'm putting your comments in checklist form here so I can keep track of my progress in addressing them.

- [x] Mention c&p lattice distance methods in paper
- [x] Move to MIT license
- [x] Fix L17 typo
- [x] Revise L42-46
- [x] Flowchart visualization (agreed this would be helpful!)
- [x] Expand description of neighborhood construction
- [x] Fix L93 monospace + typo issue

**Comment by mcgalcode** [comment]
Hi @amkrajewski,

Thanks for your comments! I have quick responses to a few of them:

pymatgen notices: I added a line in the paper saying that the implementation of methods for converting between lattice coordinates and Cartesian coordinates are taken from pymatgen (I reproduced these in `pylattica`, as opposed to importing them, because in `pymatgen` their implementation is hard-coded to use 3-dimensions, and `pylattica` enforces no such constraint). I think this emphasis reasonably reflects the degree to which `pylattica` relies on `pymatgen`. What do you think? I've also changed the license to match pymatgen's.

L42-46: Can you elaborate on the revision you'd like to see here? I'm trying to communicate that `pylattica` is built for fast prototyping and not for optimizing performance of the resulting simulations. Maybe that doesn't come across?

Neighborhood construction: I agree that there are many additional convenience classes that could be implemented to build neighborhoods! I chose to focus on motifs and radial cutoffs because they are extremely flexible. Every possible neighborhood can be represented by a motif, and radial cutoffs naturally and quickly capture the most common use cases (for instance, basic square grid neighborhood types like von Neumann and Moore are captured by radial cutoffs, and in chemistry, tetrahedral and octahedral coordination environments can be captured this way as well). I've added some of this explanation to the paper. For now, I'd prefer to limit the addition of more neighborhood types until the specific need arises.

Thanks again for your help 🙂

**Comment by amkrajewski** [comment]
Hi @mcgalcode !

### pymatgen:
In the revision I see it says:
> These structures are implemented using a `Lattice` class which uses functionality from `pymatgen` to convert coordinates between the basis of the lattice and the Cartesian basis.

which doesn't really carry the message. At the same time, your comment here explains it perfectly! With slight modification:

> These structures are implemented using a `Lattice` class which was cloned from `pymatgen` and then adjusted to the needs of `pylattica`, while mostly retaining compatibility,  primarily because current `pymatgen`'s implementation is hard-coded to use 3-dimensions, while `pylattica` strives for generality and enforces no such constraint.

Hope that helps :)

### L42-46: 
I like the content. I just meant that a style revision would be good here. In first sentence you say that performance was not the priority and in the second one that its good for applications where performance is not important. It felt a bit redundant to me.

### Neighborhood construction: 
Looks good to me!

**Comment by mcgalcode** [comment]
Hi @amkrajewski,

re: pymatgen, Thanks, that makes a lot of sense! I took your suggestion and tweaked it slightly because the `pylattica.core.Lattice` is not meant to be interoperable with the `pymatgen.Lattice` class (the connection is via their respective `Structure` classes), so I don't want to give that impression (though this is a relatively subtle distinction).

I tried to reword 42-46 as well - does that sound better?

**Comment by amkrajewski** [comment]
Both look great! 

I think the flowchart is the only missing piece. In case you didn't start working on it yet, you can try: https://github.com/jgraph/drawio-desktop
It is FOSS and has a neat functionality of embedding chart source into PNG, so you or anyone else can easily adopt or modify it later.

**Comment by mcgalcode** [comment]
That was a great suggestion! I just added a flowchart to the manuscript now.

**Comment by amkrajewski** [comment]
You may look into adding a bit more information into the flowchart on _how_ the entities are related and _why_.

At the same time, the current version does its job, so you can consider my concerns resolved 👍

**Comment by mcgalcode** [comment]
@amkrajewski Thanks for your help here - I will brainstorm ways to improve that flowchart for the documentation website :)
